"""add scan run tables for failed-ticker tracking

Revision ID: 8bd889a44df2
Revises: f2de5c68f64b
Create Date: 2026-08-19 22:24:51.098736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bd889a44df2'
down_revision: Union[str, None] = 'f2de5c68f64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_tickers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator_scan_runs')),
    sa.UniqueConstraint('scan_run_at', name=op.f('uq_indicator_scan_runs_scan_run_at'))
    )
    op.create_table('rebound_scan_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failed_tickers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebound_scan_runs')),
    sa.UniqueConstraint('scan_run_at', name=op.f('uq_rebound_scan_runs_scan_run_at'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rebound_scan_runs')
    op.drop_table('indicator_scan_runs')
    # ### end Alembic commands ###
