"""create rebound and volatility indicator scan row tables

Revision ID: f2de5c68f64b
Revises: 
Create Date: 2026-08-19 19:29:45.248980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2de5c68f64b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rebound_scan_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebound_scan_rows'))
    )
    op.create_index('ix_rebound_scan_rows_scan_run_at', 'rebound_scan_rows', ['scan_run_at'], unique=False)
    op.create_table('volatility_indicator_scan_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('threshold_pct', sa.Float(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volatility_indicator_scan_rows'))
    )
    op.create_index('ix_volatility_indicator_scan_rows_scan_run_at_threshold', 'volatility_indicator_scan_rows', ['scan_run_at', 'threshold_pct'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_volatility_indicator_scan_rows_scan_run_at_threshold', table_name='volatility_indicator_scan_rows')
    op.drop_table('volatility_indicator_scan_rows')
    op.drop_index('ix_rebound_scan_rows_scan_run_at', table_name='rebound_scan_rows')
    op.drop_table('rebound_scan_rows')
    # ### end Alembic commands ###
